### ISSUE TITLE
BugFix when EditGoodsSpec

### ISSUE THREAD

**Issue by Livins1** [ZuoFuhong/wechat-mall-backend#5]
app/infra/database/goods_infra.go

`func (c *GoodsRepos) DeleteGoodsSpec(ctx context.Context, goodsId int) error {
	empty := new(entity.WechatMallGoodsSpecDO)
	if err := c.db.Table(empty.TableName()).Where("goods_id = ?", goodsId).Update("is_del = ?", 1).Error; err != nil {
		log.ErrorContextf(ctx, "call db.Update failed, err: %v", err)
		return err
	}
	return nil
}
`
should be 
`func (c *GoodsRepos) DeleteGoodsSpec(ctx context.Context, goodsId int) error {
	empty := new(entity.WechatMallGoodsSpecDO)
	if err := c.db.Table(empty.TableName()).Where("goods_id = ?", goodsId).Update("is_del ", 1).Error; err != nil {
		log.ErrorContextf(ctx, "call db.Update failed, err: %v", err)
		return err
	}
	return nil
}`
`

**Comment by ZuoFuhong** [comment]
Thanks for your correction!
